name: Release new Version
run-name: ${{ github.actor }} is releasing a new Version 🚀
on:
  workflow_dispatch:
    inputs:
      version:
        description: Latest Harbor Version
        
jobs:
  release_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
