name: Release new Version
run-name: ${{ github.actor }} is releasing a new Version 🚀
on:
  workflow_dispatch:
    inputs:
      version:
        description: Define Harbor Version

jobs:
  release_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Update Version
        run: |
          sed -E "s/v[0-9]+\.[0-9]+\.[0-9]+/v${{ github.event.inputs.version }}/g" -i README.md
          sed -E "s/(VERSION := )v[0-9]+\.[0-9]+\.[0-9]+/\1v${{ github.event.inputs.version }}/g" -i Makefile
          make gen-harbor-api
      - name: Commit and Push Changes
        run: |
          git config user.name ${{ github.actor }}
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git checkout -B release-version-${{ github.event.inputs.version }}
          git add -A
          git commit -m "Release Version ${{ github.event.inputs.version }}"
          git push origin release-version-${{ github.event.inputs.version }}
      - name: create pull request
        run: gh pr create -B main -H release-version-${{ github.event.inputs.version }} --title 'Release Version ${{ github.event.inputs.version }}' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ github.token }}
      # todo we need to create a tag - after the merge was done!
